# Generated by Django 3.2.6 on 2021-08-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_usersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
