# Generated by Django 3.2.7 on 2021-09-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_delete_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
